config/routes.rb
GalleryJqueryFileUpload::Application.routes.draw do

  resources :galleries do
    resources :pictures do
      collection do
        post 'make_default'
      end
    end
  end
  resources :pictures

  root :to => 'galleries#index'

end

app/models/gallery.rb
class Gallery < ActiveRecord::Base
  attr_accessible :cover, :description, :name, :token

  has_many :pictures, :dependent => :destroy

  def generate_token
    self.token = loop do
      random_token = SecureRandom.urlsafe_base64
      break random_token unless Gallery.where(token: random_token).exists?
    end
  end

end

app/models/picture.rb
class Picture < ActiveRecord::Base
  attr_accessible :description, :gallery_id, :image, :crop_x, :crop_y, :crop_w, :crop_h, :gallery_token
  attr_accessor :crop_x, :crop_y, :crop_w, :crop_h

  belongs_to :gallery

  mount_uploader :image, ImageUploader

  after_update :crop_image

  def to_jq_upload
    {
      "name" => read_attribute(:image),
      "size" => image.size,
      "url" => image.url,
      "thumbnail_url" => image.thumb.url,
      "delete_url" => id,
      "picture_id" => id,
      "delete_type" => "DELETE"
    }
  end

  def crop_image
    image.recreate_versions! if crop_x.present?
    current_version = self.image.current_path
    large_version = "#{Rails.root}/public" + self.image.versions[:large].to_s

    FileUtils.rm(current_version)
    FileUtils.cp(large_version, current_version)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/galleries_controller.rb
class GalleriesController < ApplicationController
  # GET /galleries
  # GET /galleries.json
  def index
    @galleries = Gallery.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @galleries }
    end
  end

  # GET /galleries/1
  # GET /galleries/1.json
  def show
    @gallery = Gallery.find(params[:id])
    @picture = @gallery.pictures.build
    @pictures = Picture.find(:all, :conditions  => [ 'gallery_id = ?', @gallery.id ])
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/new
  # GET /galleries/new.json
  def new
    @gallery = Gallery.new
    @gallery.token = @gallery.generate_token
    @picture = @gallery.pictures.build
    @pictures = []

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @gallery }
    end
  end

  # GET /galleries/1/edit
  def edit
    @gallery = Gallery.find(params[:id])
    @picture = @gallery.pictures.build
    @pictures = []
  end

  # POST /galleries
  # POST /galleries.json
  def create
    @gallery = Gallery.new(params[:gallery])
    @pictures = Picture.where(:gallery_token => @gallery.token)
    @gallery.pictures << @pictures

    respond_to do |format|
      if @gallery.save
        format.html { redirect_to @gallery, notice: 'Gallery was successfully created.' }
        format.json { render json: @gallery, status: :created, location: @gallery }
      else
        format.html { render action: "new" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /galleries/1
  # PUT /galleries/1.json
  def update
    @gallery = Gallery.find(params[:id])

    respond_to do |format|
      if @gallery.update_attributes(params[:gallery])
        format.html { redirect_to @gallery, notice: 'Gallery was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @gallery.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /galleries/1
  # DELETE /galleries/1.json
  def destroy
    @gallery = Gallery.find(params[:id])
    @gallery.destroy

    respond_to do |format|
      format.html { redirect_to galleries_url }
      format.json { head :no_content }
    end
  end
end

app/controllers/pictures_controller.rb
class PicturesController < ApplicationController
  # GET /pictures
  # GET /pictures.json
  def index

    @gallery = Gallery.find(params[:gallery_id])

    @pictures = @gallery.pictures

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @pictures }
    end
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
    @picture = Picture.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/new
  # GET /pictures/new.json
  def new
    @gallery = Gallery.find(params[:gallery_id])
    @picture = @gallery.pictures.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @picture }
    end
  end

  # GET /pictures/1/edit
  def edit
    @gallery = Gallery.find(params[:gallery_id])

    @picture = @gallery.pictures.find(params[:id])
    # @picture = Picture.find(params[:id])
  end

  # POST /pictures
  # POST /pictures.json
  def create
    p_attr = params[:picture]
    p_attr[:image] = params[:picture][:image].first if params[:picture][:image].class == Array

    if params[:gallery_id]
      @gallery = Gallery.find(params[:gallery_id])
      @picture = @gallery.pictures.build(p_attr)
    else
      @picture = Picture.new(p_attr)
    end

    if @picture.save
      respond_to do |format|
        format.html {
          render :json => [@picture.to_jq_upload].to_json,
          :content_type => 'text/html',
          :layout => false
        }
        format.json {
          render :json => [@picture.to_jq_upload].to_json
        }
      end
    else
      render :json => [{:error => "custom_failure"}], :status => 304
    end
  end

  # PUT /pictures/1
  # PUT /pictures/1.json
  def update

    @gallery = Gallery.find(params[:gallery_id])

    @picture = @gallery.pictures.find(params[:id])

    respond_to do |format|
      if @picture.update_attributes(params[:picture])
        format.html { redirect_to gallery_path(@gallery), notice: 'Picture was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @gallery = Gallery.find(params[:gallery_id])
    @picture = @gallery.pictures.find(params[:id])
    @picture.destroy

    respond_to do |format|
      format.html { redirect_to gallery_pictures_url }
      format.js
    end
  end

  def make_default
    @picture = Picture.find(params[:id])
    @gallery = Gallery.find(params[:gallery_id])

    @gallery.cover = @picture.id
    @gallery.save

    respond_to do |format|
      format.js
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/galleries_helper.rb
module GalleriesHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/galleries/_form.html.erb
<%= form_for @gallery, :html => { :class => 'form-horizontal' } do |f| %>
  <%= f.hidden_field :token %>
  <div class="control-group">
    <%= f.label :name, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :name, :class => 'text_field' %>
    </div>
  </div>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-mini btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                galleries_path, :class => 'btn btn-mini' %>
  </div>
<% end %>


<%= form_for @picture, :html => { :multipart => true, :id => "fileupload"  } do |f| %>
  <div class="row">
    <%= f.hidden_field :gallery_token, value: @gallery.token %>

    <div class=" fileupload-buttonbar">
      <div class="progressbar fileupload-progressbar nofade"><div style="width:0%;"></div></div>
      <span class="btn btn-mini fileinput-button">
        <i class="icon-plus"></i>
        <span><%= t('photos.add_files') %>...</span>
        <%= f.file_field :image, :multiple => true %>
      </span>
    </div>
  </div>

  <h2>Pictures</h2>
  <br>
  <div class="row">
    <ul class="thumbnails files">
    </ul>
  </div>
<% end %>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>

<script id="template-download" type="text/html">
  {% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
  <tr class="template-download nofade">
    {% if (file.error) { %}
    <td></td>
    <td class="name">{%=file.name%}</td>
    <td class="size">{%=o.formatFileSize(file.size)%}</td>
    <td class="error" colspan="2"><span class="label important">Error</span> {%=fileUploadErrors[file.error] || file.error%}</td>
    {% } else { %}
    <td class="preview">{% if (file.thumbnail_url) { %}
      <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery"><img src="{%=file.thumbnail_url%}"></a>
    {% } %}</td>
    <td class="name">
      <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}">{%=file.name%}</a>
    </td>
    <td class="size">{%=o.formatFileSize(file.size)%}</td>
    <td colspan="2"></td>
    {% } %}
    <td class="delete">
    <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"><%= t('photos.template.delete') %></button>
    <input type="checkbox" name="delete" value="1">
    </td>
  </tr>
  {% } %}
</script>

<%= javascript_include_tag 'jquery.ui.widget.js' %>
<%= javascript_include_tag 'jquery.iframe-transport.js' %>
<%= javascript_include_tag 'jquery.fileupload.js' %>
<%= javascript_include_tag 'jquery.fileupload-ui.js' %>

app/views/galleries/edit.html.erb
<%- model_class = @gallery.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                   :default => "Edit #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/index.html.erb
<div class="row">
  <h1>Galleries</h1>
  <ul class="thumbnails files">
    <% @galleries.each do |gallery| %>
        <li class="span3" id="gallery_<%= gallery.id %>">
          <div class="thumbnail">
            <% if gallery.cover.blank? or !Picture.find_by_id(gallery.cover) %>
              <a href="<%= gallery_path(:id => gallery.id) %>">
                <img src="/assets/NoImageAvailable.jpg" alt="">
              </a>
            <% else %>
              <a href="<%= gallery_path(:id => gallery.id) %>">
                <img src="<%= Picture.find_by_id(gallery.cover).image.thumb.url %>" alt="">
              </a>
            <% end %>
            <div class="caption">
              <p style="text-align: center;">
                <%= gallery.name.truncate(14) %>
                <a href="<%= edit_gallery_path(:id => gallery.id) %>" class="btn btn-mini">
                  <i class="icon-edit "></i>
                  Edit
                </a>
                <a class="btn btn-mini btn-delete" confirm="Вы уверены?" data-method="delete" href="<%= gallery_path(:id => gallery.id) %>" data-remote=true>
                  <i class="icon-trash"></i>
                  Delete
                </a>
              </p>
            </div>
          </div>
        </li>
    <% end %>
  </ul>

  <%= link_to 'New', new_gallery_path, :class => 'btn btn-mini' %>
</div>

app/views/galleries/new.html.erb
<%- model_class = @gallery.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/galleries/show.html.erb
<div class="row">
  <h1>Gallery</h1>

  <input type="hidden" id="galleryID" value="<%= @gallery.id %>">

  <p>
    <b>Name: </b>
    <%= @gallery.name %>
  </p>

  <p>
    <b>Description: </b>
    <%= @gallery.description %>
  </p>

<h2>Pictures</h2>
</div>

<%= form_for [@gallery, @picture], :html => { :multipart => true, :id => "fileupload"  } do |f| %>
  <div class="row">
    <div class=" fileupload-buttonbar">
      <div class="progressbar fileupload-progressbar nofade"><div style="width:0%;"></div></div>
      <span class="btn btn-mini fileinput-button">
        <i class="icon-plus"></i>
        <span><%= t('photos.add_files') %>...</span>
        <%= f.file_field :image, :multiple => true %>
      </span>
    </div>
  </div>
  <br>
  <div class="row">
    <ul class="thumbnails files">
      <% unless @pictures.empty? %>
        <% @pictures.each do |pic| %>
            <li class="span3" id="picture_<%= pic.id %>">
              <div class="thumbnail">
                <a href="<%= pic.image.url %>" rel="lightbox-pictures" title="<%= pic.description %>">
                  <img src="<%= pic.image.thumb.url %>" alt="">
                </a>
                <div class="caption">
                  <p style="text-align: center;">
                    <a href="/galleries/<%= @gallery.id %>/pictures/<%= pic.id %>/edit" class="btn btn-mini">
                      <i class="icon-edit "></i>
                      Edit
                    </a>
                    <a class="btn btn-mini btn-delete" confirm="Вы уверены?" data-method="delete" href="/galleries/<%= @gallery.id %>/pictures/<%= pic.id %>" data-remote=true>
                      <i class="icon-trash"></i>
                      Delete
                    </a>
                  </p>
                </div>
              </div>
            </li>
        <% end %>
      <% end %>
    </ul>
  </div>
<% end %>
<script>
  var fileUploadErrors = {
    maxFileSize: 'File is too big',
    minFileSize: 'File is too small',
    acceptFileTypes: 'Filetype not allowed',
    maxNumberOfFiles: 'Max number of files exceeded',
    uploadedBytes: 'Uploaded bytes exceed file size',
    emptyResult: 'Empty file upload result'
  };
</script>



<script id="template-download" type="text/html">
  {% for (var i=0, files=o.files, l=files.length, file=files[0]; i<l; file=files[++i]) { %}
  <tr class="template-download nofade">
    {% if (file.error) { %}
    <td></td>
    <td class="name">{%=file.name%}</td>
    <td class="size">{%=o.formatFileSize(file.size)%}</td>
    <td class="error" colspan="2"><span class="label important">Error</span> {%=fileUploadErrors[file.error] || file.error%}</td>
    {% } else { %}
    <td class="preview">{% if (file.thumbnail_url) { %}
      <a href="{%=file.url%}" title="{%=file.name%}" rel="gallery"><img src="{%=file.thumbnail_url%}"></a>
    {% } %}</td>
    <td class="name">
      <a href="{%=file.url%}" title="{%=file.name%}" rel="{%=file.thumbnail_url&&'gallery'%}">{%=file.name%}</a>
    </td>
    <td class="size">{%=o.formatFileSize(file.size)%}</td>
    <td colspan="2"></td>
    {% } %}
    <td class="delete">
    <button class="btn btn-danger" data-type="{%=file.delete_type%}" data-url="{%=file.delete_url%}"><%= t('photos.template.delete') %></button>
    <input type="checkbox" name="delete" value="1">
    </td>
  </tr>
  {% } %}
</script>



<%= javascript_include_tag 'jquery.ui.widget.js' %>
<%= javascript_include_tag 'jquery.iframe-transport.js' %>
<%= javascript_include_tag 'jquery.fileupload.js' %>
<%= javascript_include_tag 'jquery.fileupload-ui.js' %>




<div class="row">
  <div class="form-actions">
    <%= link_to 'Back', galleries_path, :class => 'btn btn-mini'  %>
    <%= link_to 'Edit', edit_gallery_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Delete', gallery_path(@gallery), :method => 'delete', :confirm => 'Are you sure?', :class => 'btn btn-mini' %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GalleryJqueryFileUpload</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<div class="container">
  <div class="row">
    <div class="span8"><%= yield %></div>
  </div>
</div>

</body>
</html>

app/views/pictures/_form.html.erb
<%= form_for [@gallery, @picture], :html => { :class => 'form-horizontal' } do |f| %>
  <div class="control-group">
    <%= f.label :description, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :description, :class => 'text_field' %>
    </div>
  </div>
  
    <%= image_tag @picture.image.large.url, :id => 'cropbox' %>
  
  <% %w[x y w h].each do |attribute| %>
    <%= f.hidden_field "crop_#{attribute}" %>
  <% end %>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary  btn-mini' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                gallery_path(@gallery), :class => 'btn btn-mini' %>
    <%= link_to 'Default', '', :class => 'btn btn-mini btn-success' , :id => 'make_default'%>

  </div>
<% end %>

<script type="text/javascript" charset="utf-8">
    $(function () {
      $('#make_default').click(function(event) {
        event.preventDefault();
        $.ajax({
          url: '<%= make_default_gallery_pictures_path %>',
          type: 'POST',
          data: {id : <%= @picture.id %>, gallery_id : <%= @gallery.id %>}
        });
      });
    });
</script>

app/views/pictures/destroy.js.erb
$('#picture_<%= @picture.id %>').fadeOut();

app/views/pictures/edit.html.erb
<div class="page-header">
  <h1>Edit Picture</h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/index.html.erb
<%- model_class = Picture.new.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:description) %></th>
      <th><%= model_class.human_attribute_name(:image) %></th>
      <th><%= model_class.human_attribute_name(:gallery_id) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @pictures.each do |picture| %>
      <tr>
        <td><%= link_to picture.id, picture_path(picture) %></td>
        <td><%= picture.description %></td>
        <td><%= picture.image %></td>
        <td><%= picture.gallery_id %></td>
        <td><%=l picture.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_picture_path(picture), :class => 'btn btn-mini' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      picture_path(picture),
                      :method => :delete,
                      :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
                      :class => 'btn btn-mini btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_picture_path,
            :class => 'btn btn-primary' %>

app/views/pictures/make_default.js.erb
$('<span style="color: #46a546; margin-left: 15px; font-weight: bold;">Done!</span>').insertAfter('#make_default').delay(3000).fadeOut('slow');

app/views/pictures/new.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/pictures/show.html.erb
<%- model_class = @picture.class -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:description) %>:</strong></dt>
  <dd><%= @picture.description %></dd>
  <dt><strong><%= model_class.human_attribute_name(:image) %>:</strong></dt>
  <dd><%= @picture.image %></dd>
  <dt><strong><%= model_class.human_attribute_name(:gallery_id) %>:</strong></dt>
  <dd><%= @picture.gallery_id %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              pictures_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_picture_path(@picture), :class => 'btn' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              picture_path(@picture),
              :method => 'delete',
              :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')),
              :class => 'btn btn-danger' %>
</div>